name: Project-1-IaC-Security Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  iac-security:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7

      - name: Terraform Init
        run: terraform -chdir=./Project-1-IaC-Security init

      - name: Terraform Plan
        run: terraform -chdir=./Project-1-IaC-Security plan

      - name: Terraform Apply
        run: terraform -chdir=./Project-1-IaC-Security apply -auto-approve
