name: IaC Security Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  iac-security:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      # Optional: List files to confirm your directory structure
      - name: List files in root
        run: ls -al

      - name: List files in Project-1 folder
        run: ls -al Project-1-IaC-Security

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7

      # Initialize Terraform in the Project 1 folder
      - name: Terraform Init
        run: terraform init
        working-directory: ./Project-1-IaC-Security

      # (Optional) Terraform Plan
      - name: Terraform Plan
        run: terraform plan
        working-directory: ./Project-1-IaC-Security

      # Install Trivy
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin

      # Run Trivy IaC Scan on the Project 1 folder
      - name: Trivy IaC Scan
        run: trivy config --exit-code 1 --severity HIGH,CRITICAL ./Project-1-IaC-Security

      # (Optional) Terraform Apply (be cautious in production)
      # - name: Terraform Apply
      #   run: terraform apply -auto-approve
      #   working-directory: ./Project-1-IaC-Security