name: IaC Security Scan  # 👈 Name of the workflow

on:
  push:
    paths:
      - 'Project-1-IaC-Security/**/*.tf'   # 👈 Only trigger if Terraform files in Project 1 change
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  checkov-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Checkov on Project 1 Terraform
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ./Project-1-IaC-Security  # 👈 Only scan this project folder
          framework: terraform