name: Project-2-Container-Security Push

on:
  workflow_dispatch:  # Manual trigger for push, ensuring you've scanned the image first
  # Optionally, you could trigger on a tag or a specific branch:
  # push:
  #   branches: [ "production" ]
  #   paths:
  #     - "Project-2-Container-Security/**"

jobs:
  push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build Docker Image
        working-directory: ./Project-2-Container-Security
        run: docker build -t project-2-secure-app:latest .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Tag Docker Image
        run: docker tag project-2-secure-app:latest ${{ secrets.DOCKERHUB_USERNAME }}/project-2-secure-app:latest

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/project-2-secure-app:latest