name: Project-2-Container-Security Pipeline

on:
  push:
    branches: [ "main" ]
    paths:
      - "Project-2-Container-Security/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "Project-2-Container-Security/**"

jobs:
  build-scan-push:
    name: Build, Scan, and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build Docker Image
        working-directory: ./Project-2-Container-Security
        run: docker build -t project-2-secure-app:latest .

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh \
          | sudo sh -s -- -b /usr/local/bin

      - name: Scan Docker Image with Trivy
        run: trivy image --exit-code 1 --severity HIGH,CRITICAL project-2-secure-app:latest

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" \
          | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Tag Docker Image
        run: docker tag project-2-secure-app:latest "${{ secrets.DOCKERHUB_USERNAME }}/project-2-secure-app:latest"

      - name: Push Docker Image
        run: docker push "${{ secrets.DOCKERHUB_USERNAME }}/project-2-secure-app:latest"